export const browserCoreExamples = [
  "draftclaw browser status",
  "draftclaw browser start",
  "draftclaw browser stop",
  "draftclaw browser tabs",
  "draftclaw browser open https://example.com",
  "draftclaw browser focus abcd1234",
  "draftclaw browser close abcd1234",
  "draftclaw browser screenshot",
  "draftclaw browser screenshot --full-page",
  "draftclaw browser screenshot --ref 12",
  "draftclaw browser snapshot",
  "draftclaw browser snapshot --format aria --limit 200",
  "draftclaw browser snapshot --efficient",
  "draftclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "draftclaw browser navigate https://example.com",
  "draftclaw browser resize 1280 720",
  "draftclaw browser click 12 --double",
  'draftclaw browser type 23 "hello" --submit',
  "draftclaw browser press Enter",
  "draftclaw browser hover 44",
  "draftclaw browser drag 10 11",
  "draftclaw browser select 9 OptionA OptionB",
  "draftclaw browser upload /tmp/file.pdf",
  'draftclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "draftclaw browser dialog --accept",
  'draftclaw browser wait --text "Done"',
  "draftclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "draftclaw browser console --level error",
  "draftclaw browser pdf",
];
